### ISSUE TITLE
make curb work with latest libcurl

### ISSUE THREAD

**Issue by Eliada** [taf2/curb#385]
Hi!

### Question:

What would be the steps required to update the gem in order for it to work with newer versions of `libcurl`?

I saw in the [readme](https://github.com/taf2/curb#version-compatibility-chart) that the latest version of curb only runs until the version 7.63 of libcurl, and I started to wonder what would take to make it work with 7.64

### Some Context

I've recently updated my ubuntu to 19.04 and with that the version of curl has gone up:
```
$ curl --version
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.6/openssl/zlib nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```
so attempting to install the gem causes an error:
```
compiling curb_errors.c
curb_errors.c: In function ‘rb_curl_easy_error’:
curb_errors.c:324:5: error: duplicate case value
     case CURLE_SSL_CACERT:              /* 60 - problem with the CA cert (path?) */
     ^~~~
curb_errors.c:297:5: note: previously used here
     case CURLE_SSL_PEER_CERTIFICATE:    /* 51 - peer's certificate wasn't ok */
     ^~~~
```
I was about to downgrade libcurl, but then I though that instead I could make a pull request in the gem so it would work with libcurl 7.64. But I don't know where to start :sweat_smile:

**Comment by robuye** [comment]
Hi @Eliada, I think this should be already fixed in current curb version, can you try upgrading?

**Comment by Eliada** [comment]
Thanks, it worked!

**Comment by Eliada** [comment]
But still... how hard it is to make curb work with new versions of libcurl?
I was attempting to make a pull request. In the case of a new version of libcurl I might still be

**Comment by robuye** [comment]
Hey @Eliada,

It was a breaking change introduced in libcurl 7.62.0 that caused Curb to fail to build & it was fixed in #367. Curb is expected to work with all versions of libcurl and if it doesn't it's a bug that gets fixed and a new version is released. There's no easy way around future breaking changes in libcurl (or anything really) and any fixes to curb (or anything) require a new version to be released (and as a consequence of this users need to upgrade too).

Curb does work with all libcurl versions *by default*, it's only the breaking changes that break compatibility forward (backward compatibility is always maintained). 

Hope that gives you a better picture of what happened and why it stopped working. And thanks for an attempt to fix it too, it shows you care about curb :bowing_man:

**Comment by luke-hill** [comment]
Also just to point out the link you mentioned. I added that to the readme as a "safe" set of version restrictions.

i.e. these versions 100% work, because people have tried them on a couple of Operating Systems and Machines. That's not to say other versions won't work, just that we "don't know".

If you have time and have got proof of a variety of libcurl versions against a variety of the gem versions, please feel free to let us know and we/you can amend that portion of the README accordingly.

Going forward until Bionic releases an update I'm more than happy using 7.58 (Which is what Bionic-1 ships with), which gives me a reasonable amount of functionality and bug fixes/protection.

Hope that helps.

**Comment by Eliada** [comment]
I believe you answered the issue. I'm closing it if it's okay
