### ISSUE TITLE
curb installation fails with newest curl (7.63)

### ISSUE THREAD

**Issue by meal** [taf2/curb#377]
### Environment

* OS: macOS Mojave / Arch Linux
* RVM
* ruby: 2.5.1 / 2.5.3
* curb: 0.9.6
* openssl 1.1.1a
* curl: 7.63

### What happens
Building native extension for `curb` fails

```
creating Makefile

current directory: /Users/meal/.rvm/gems/ruby-2.5.1/gems/curb-0.9.6/ext
make "DESTDIR=" clean

current directory: /Users/meal/.rvm/gems/ruby-2.5.1/gems/curb-0.9.6/ext
make "DESTDIR="
compiling curb.c
compiling curb_easy.c
curb_easy.c:1006:3: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
  CURB_IMMED_SETTER(ruby_curl_easy, proxy_type, -1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./curb_macros.h:110:27: note: expanded from macro 'CURB_IMMED_SETTER'
              ptr->attr = NUM2LONG(attr);                           \
                        ~ ^~~~~~~~~~~~~~
/Users/meal/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0/ruby/ruby.h:650:21: note: expanded from macro 'NUM2LONG'
#define NUM2LONG(x) RB_NUM2LONG(x)
                    ^~~~~~~~~~~~~~
/Users/meal/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0/ruby/ruby.h:649:24: note: expanded from macro 'RB_NUM2LONG'
#define RB_NUM2LONG(x) rb_num2long_inline(x)
                       ^~~~~~~~~~~~~~~~~~~~~
curb_easy.c:3320:34: warning: implicit conversion loses integer precision: 'long' to 'CURLoption' [-Wshorten-64-to-32]
    curl_easy_setopt(rbce->curl, option, NUM2LONG(value));
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/curl/7.63.0/include/curl/curl.h:2813:68: note: expanded from macro 'curl_easy_setopt'
#define curl_easy_setopt(handle,opt,param) curl_easy_setopt(handle,opt,param)
                                           ~~~~~~~~~~~~~~~~        ^~~
2 warnings generated.
compiling curb_errors.c
curb_errors.c:337:10: error: duplicate case value 'CURLE_PEER_FAILED_VERIFICATION'
    case CURLE_SSL_CACERT:              /* 60 - problem with the CA cert (path?) */
         ^
/usr/local/Cellar/curl/7.63.0/include/curl/curl.h:603:26: note: expanded from macro 'CURLE_SSL_CACERT'
#define CURLE_SSL_CACERT CURLE_PEER_FAILED_VERIFICATION
                         ^
curb_errors.c:310:10: note: previous case defined here
    case CURLE_SSL_PEER_CERTIFICATE:    /* 51 - peer's certificate wasn't ok */
         ^
/usr/local/Cellar/curl/7.63.0/include/curl/curl.h:610:36: note: expanded from macro 'CURLE_SSL_PEER_CERTIFICATE'
#define CURLE_SSL_PEER_CERTIFICATE CURLE_PEER_FAILED_VERIFICATION
                                   ^
1 error generated.
make: *** [curb_errors.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/meal/.rvm/gems/ruby-2.5.1/gems/curb-0.9.6 for inspection.
Results logged to /Users/meal/.rvm/gems/ruby-2.5.1/extensions/x86_64-darwin-17/2.5.0/curb-0.9.6/gem_make.out
```

### Steps to reproduce
Put `gem 'curb'` in your Gemfile and try to `bundle` it

**Comment by robuye** [comment]
@meal from the logs it seems you're using curb `0.9.6` and this bug has been in `0.9.7`.

I have tested on `0.9.8` and it compiles correctly. Can you give it a try?

**Comment by meal** [comment]
@robuye It works fine on `0.9.8`, I've missed it was locked to `0.9.6` in Gemfile, thanks!

**Comment by Nikhil-Wagh** [comment]
I'm also getting the same error, and the solution described here will not work for me as I specifically want `curb -v 0.8.5`
 
##  Environment
- OS: macOS Catalina
- RVM
- ruby 2.0.0p247
- curb 0.8.5
- openssl - LibreSSL 2.8.3
- curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
