### ISSUE TITLE
ruby 2.2.1 on osx 10.8.5 and rvm

### ISSUE THREAD

**Issue by oprema** [taf2/curb#241]
I get the following error while installing the gem:

```
checking for curlm_bad_socket... yes
checking for curlm_unknown_option... yes
checking for curl_multi_timeout()... yes
checking for curl_multi_fdset()... yes
checking for curl_multi_perform()... yes
checking for Ruby 1.9 Hash... no
checking for Ruby 1.9 st.h... yes
checking for curl_easy_escape... yes
creating curb_config.h
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling curb.c
compiling curb_easy.c
curb_easy.c:2614:69: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
  result = (char*)curl_easy_escape(rbce->curl, StringValuePtr(str), RSTRING_LEN(str));
                  ~~~~~~~~~~~~~~~~                                  ^~~~~~~~~~~~~~~~
/Users/joe/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/ruby.h:863:6: note: expanded from macro 'RSTRING_LEN'
     RSTRING_EMBED_LEN(str) : \
     ^~~~~~~~~~~~~~~~~~~~~~
/Users/joe/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/ruby.h:859:6: note: expanded from macro 'RSTRING_EMBED_LEN'
     (long)((RBASIC(str)->flags >> RSTRING_EMBED_LEN_SHIFT) & \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
curb_easy.c:2614:69: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
  result = (char*)curl_easy_escape(rbce->curl, StringValuePtr(str), RSTRING_LEN(str));
                  ~~~~~~~~~~~~~~~~                                  ^~~~~~~~~~~~~~~~
/Users/joe/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/ruby.h:864:28: note: expanded from macro 'RSTRING_LEN'
     RSTRING(str)->as.heap.len)
     ~~~~~~~~~~~~~~~~~~~~~~^~~
curb_easy.c:2642:71: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
  result = (char*)curl_easy_unescape(rbce->curl, StringValuePtr(str), RSTRING_LEN(str), &rlen);
                  ~~~~~~~~~~~~~~~~~~                                  ^~~~~~~~~~~~~~~~
/Users/joe/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/ruby.h:863:6: note: expanded from macro 'RSTRING_LEN'
     RSTRING_EMBED_LEN(str) : \
     ^~~~~~~~~~~~~~~~~~~~~~
/Users/joe/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/ruby.h:859:6: note: expanded from macro 'RSTRING_EMBED_LEN'
     (long)((RBASIC(str)->flags >> RSTRING_EMBED_LEN_SHIFT) & \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
curb_easy.c:2642:71: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
  result = (char*)curl_easy_unescape(rbce->curl, StringValuePtr(str), RSTRING_LEN(str), &rlen);
                  ~~~~~~~~~~~~~~~~~~                                  ^~~~~~~~~~~~~~~~
/Users/joe/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/ruby.h:864:28: note: expanded from macro 'RSTRING_LEN'
     RSTRING(str)->as.heap.len)
     ~~~~~~~~~~~~~~~~~~~~~~^~~
4 warnings generated.
compiling curb_errors.c
curb_errors.c:447:33: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
  rb_raise(rb_ary_entry(obj,0), RSTRING_PTR(rb_ary_entry(obj,1)));
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/joe/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/ruby.h:866:5: note: expanded from macro 'RSTRING_PTR'
    (!(RBASIC(str)->flags & RSTRING_NOEMBED) ? \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
curb_errors.c:495:33: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
  rb_raise(rb_ary_entry(obj,0), RSTRING_PTR(rb_ary_entry(obj,1)));
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/joe/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/ruby.h:866:5: note: expanded from macro 'RSTRING_PTR'
    (!(RBASIC(str)->flags & RSTRING_NOEMBED) ? \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
compiling curb_multi.c
curb_multi.c:68:79: warning: implicit declaration of function 'RHASH' is invalid in C99 [-Wimplicit-function-declaration]
  if (rbcm && !rbcm->requests == Qnil && rb_type(rbcm->requests) == T_HASH && RHASH_LEN(rbcm->requests) > 0) {
                                                                              ^
./curb.h:43:27: note: expanded from macro 'RHASH_LEN'
  #define RHASH_LEN(hash) RHASH(hash)->tbl->num_entries
                          ^
curb_multi.c:68:79: error: member reference type 'int' is not a pointer
  if (rbcm && !rbcm->requests == Qnil && rb_type(rbcm->requests) == T_HASH && RHASH_LEN(rbcm->requests) > 0) {
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
./curb.h:43:40: note: expanded from macro 'RHASH_LEN'
  #define RHASH_LEN(hash) RHASH(hash)->tbl->num_entries
                          ~~~~~~~~~~~  ^
curb_multi.c:444:10: warning: implicit declaration of function 'rb_thread_select' is invalid in C99 [-Wimplicit-function-declaration]
    rc = rb_thread_select(maxfd+1, &fdread, &fdwrite, &fdexcep, &tv);
         ^
2 warnings and 1 error generated.
make: *** [curb_multi.o] Error 1

make failed, exit code 2
```

**Comment by grepruby** [comment]
I have same issue on Ubuntu 12 as well with ruby 2.2.1

Any fix ?

**Comment by tnlin** [comment]
same here

**Comment by rbgraham** [comment]
I was able to install by specifying lib and include after `brew install curl` to make sure I had the development libraries. I'm not sure the packaged OS X curl has development headers and such.

`gem install curb --platform=ruby -- --with-curl-lib=/usr/local/opt/curl/lib --with-curl-include=/usr/local/opt/curl/include`

Worked on OS X 10.10.3

**Comment by wtfiwtz** [comment]
@rbgraham solution works for curb 0.8.8 on OS X 10.11.1, but not for curb 0.8.0, so you might need to be on the latest version of the gem.

Here's my gcc details:

    Nigel-MBP:~ wtfiwtz$ gcc -v
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 7.0.0 (clang-700.1.76)
    Target: x86_64-apple-darwin15.0.0
    Thread model: posix

**Comment by Cueroqu** [comment]
I have the same issue when installing a previous version 0.7.12, and @rbgraham solution didn't work either. Anyone know how to fix it? ruby 2.2.1 and mac os x 10.11
